### PR TITLE
implement dane's changes to rebar to make it faster

### PR DESCRIPTION
**Pull request by ssawan623**
## Things Done:
- this is how Dane made rebar 'faster'. I wanna have start tracking these kinds of changes in our own forked `rebar3`. Take a look.

## How To Test
- build this `rebar3` using `./bootstrap`
- anything the old Dane-flavored script can do, this one can do (and hopefully better considering this is based on a newer version of rebar)

## Next Steps
- throw this built version of rebar in `vhx` source in the `vhx_scripts` directory

### CODE REVIEW

**Review by edunnell — APPROVED** [review]
👍

**Review by rherro — APPROVED** [review]
👍

**Review by mnash88 — APPROVED** [review]
:+1:

**Comment by rherro** [comment]
Just curious, what is the functionality that was removed?  And would it be better to put this version of rebar in the base of the project instead or is this just used if all of the dependencies have already been pulled down?

**Comment by ssawan623** [comment]
@rherro this seems to be the request that was taken out
```erlang
httpc:request(get, {Url, [{"User-Agent", rebar_utils:user_agent()}]},
                                           [], [{stream, TmpFile}, {sync, true}],
                                           rebar)
```
Then, later down...
```erlang
{ok, Data} = file:read_file(TmpFile),
Unzipped = zlib:gunzip(Data),
ok = file:write_file(HexFile, Unzipped),
```
What exactly it does I don't know, @dbills can enlighten us! I'm pretty sure it just stops up from rewriting a registry over and over when there is no need to.

I'm gonna do some testing with this `rebar3` whenever I get my Vagrant machine in a decent state, but if I remember correctly, this does not work if the dependencies haven't been pulled down first.

EDIT: yeah, this bit of code keeps writing the 'package registry index' when there is probably not a need to.

**Comment by rherro** [comment]
Cool, thanks for the info @ssawan623!  😄

**Comment by ssawan623** [comment]
@rherro after some testing, this rebar3 cannot be run unless the 'normal' rebar3 is run first.

**Pull request merged**
